### ISSUE TITLE
promotion policy

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#15]
A supercool way to promote, click on piece and the piece to move become a piece, on starting position and arrow up arrow down change it, i suggest queen as a default promo, arrow down make it rook, bishop. knith, because is selected by mouse wheel should be able to turn the piece. I think this is original and super fast! :+1: 

if a pawn in  relative 7 rank is selected ad piece to move in square from, add a box with piece to promote and a box to tickle (automatic promotion)
if not automoatic promotion then open box to select piece every time
if automatic then promote the selected piece (after tickle)
if piece is selected by mistake there should be a cancel button that allow to deselect squarefrom.

To remove automatic promotion, add a tickle box on board box actions (resign, draw ...) to deselect (show only if is selected or show ever and if tickled popup piece to promote choice, but i dont like this last solution, less things are on box better is readable, then faster is to do actions)

Another possibilities is 
if not square from is selectd when pawn is on relative 7 rank and piece is not yet selected but just mouse pointers is on it (touch square event) on piece, then open a menu with same behaviour,  but this could be really ennoying, if your piece to move is on the trajectory of where is mouse and where is going to select piece.

select piece to promote or set automatically in this case thereis no needd of the menu event control, wich  means, faster client faster user move.

**Comment by drestebon** [comment]
I believe simple solutions are always best. Promotion is controlled with the `promotion` command and is always available, this means that you dont need to select a pawn that could be promoted, in order to change it. I believe that if our gui is going to provide easy access to options availible in the server (as issuing moves through a gui!) it should do it in the most easy and natural way possible. In this sense, a keybinding for cycling through the options seems to me as a simple and fast solution. I added this through the `Tab` binding in the last push.

What do you think?

**Comment by enricoT** [comment]
fantastic i couldnt ask better! :+1: 
And, the flag stays saved for the next promotion! that's cool!
And even better i can activate promotion also when is not selected the pawn!
