### ISSUE TITLE
copy and past or select is not allowed on console

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#2]
it would be nice to copy & paste or select (double button emulation is useful) to redirect address links or to answer fast to a player clicking on is name

**Comment by drestebon** [comment]
Hey enrico T, thank you for your feedback, it is really valuable!

The default behaviour for papageorge is to handle mouse events, so that you can click on an user handle to issue commands on him or click on a move in algebraic notation to issue it. The later is very useful when you are analyzing games with analyzebot. I do not believe this can be turned on and off on the fly, so I will add an option to the configuration file to disable the default behaviour.

**Comment by drestebon** [comment]
Option added

**Comment by enricoT** [comment]
i m not sure, i cannot copy or paste for the moment as i already suggested in precedent fix, it woud be nice to move left button mouse on right button, and use left mouse on copy & paste & select, this standard on every client (go, chess... whatever :)

**Comment by drestebon** [comment]
See #4
