### ISSUE TITLE
console click on handle

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#4]
the mouse should by default fly on tell button to talk faster

**Comment by drestebon** [comment]
done

**Comment by enricoT** [comment]
wait i click on name window popup but i have to move mouse on the button it's not redirected by default, another suggest is console click on handle should work on right mouse and left mouse should be used to copy paste and select from console.

**Comment by drestebon** [comment]
I dont think moving the mouse should be a feature of an app. Note that if the dialog is focused, pressing enter will trigger the default action, which in this case is set to "tell". Regarding the behavior of the mouse on the console, because of the console library we are using, it would add a lot of complexity to set things up as you suggest. However! It allows to use copy and paste as usual if you hold the shift key, says the documentation. I will test it and add it to the readme.

**Comment by enricoT** [comment]
:+1: 
I dont know if its the case about testing if is a htpp: or www. allow to call browser from gui? I think it's possible from raptor and babas but i dont know about multiplatform behaviour

**Comment by drestebon** [comment]
It is part of the design not to redo the wheel. That was the thinking behind using the terminal emulator and an existing CLI library. I know urxvt marks URLs and calls the browser on it after a few keystrokes. I guess other modern terminal emulators should have such an option also.
