### ISSUE TITLE
load pgn

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#49]
i open examine
and load game from base 
nothing happpens this is pgn format:

http://pastebin.com/ma8vC79w

nice to see you

**Comment by drestebon** [comment]
Hello enricoT,

When loading a pgn file to an examine game, you can navigate through the loaded moves using the move sheet, which you activate with ctrl+space in the default setup.

Still, there was a lot of problems with the move sheet and pgn-loading, which I hopefully fixed in the commit 680ae6a952acc065ff312e8524993022b4fd76a.
