### ISSUE TITLE
examine uploaded game

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#50]
ctrl space activate examine loaded pg
any move out of path loaded inserted from board crashes the pg client i have reopen papageorge and reconnect

**Comment by enricoT** [comment]
is possible to open ctrl space sheet before loading pgn wich causes a crashe when you upload the pgn Movetree object has no attribute cli ...

**Comment by drestebon** [comment]
Hey enrico, I am figuring, there a lot more issues than I though in the implementation of the move sheet. I will have to rethink things! I will keep you posted!

**Comment by enricoT** [comment]
the tree of moves should be edit/view mode, adding new move or old move should be read by sheet and by mouse move, this means no control on legality, server willcheck and answer about that i suggest to focus on: add move, play old move, clean move/tree if there are more moves sub variation. The graphic way to show sheet is not important now, maybe just adding a right mouse menu on move to add, enter or clean move is enough...

**Comment by enricoT** [comment]
new move only from mouse, jumping from tree to position from sheet only clicking moves on sheet, clean all moves from board position should go from sheet mouse menu, jump to next subvariantion , jump to precedent variation, same sheet mouse menu. Save pgn with all new variation at the exit (unexamine) wich could be from mouse or from console command. Remember that in examine you can add move from console and from board mouse click.

**Comment by enricoT** [comment]
The sheet menu should always focus red the position board/move on sheet list allowing for that move only adding deleting commenting jump to precedent var jump to next var.

**Comment by drestebon** [comment]
Hello enricoT,

Thank you very much for the feedback.

This is how the move sheet works: it is a representation of the history of the current game. Every move done in the board should be represented in it (including variations!). When you left-click on a cell, the board shows the state of the game after that move was made. When you right-click on a cell, a menu is displayed. Currently, with the menu you can only edit or remove a comments for the moves, but I plan to include the following options:

```
- promote variation to main
- delete variation
- delete move
```

There is also the possibility, that new variations not connected to the mainline appear. I plan to add a way to display them as well.

Note that moves are added to the move sheet only through the board. I believe this makes more sense, than adding moves through the move sheet. I don't like the idea of including a "PGN file editor" in papageorge, since you can do that with a text editor. Still, I think is good enough to be able to move pieces around in a board and then saving the result as PGN, which is what papageorge currently does.

Backward and forward commands (right and left arrow keys) go forwards and backwards on the mainline only. For examine games, that is the main-line in the server. To move forward on the moves loaded from a PGN file, you have to use the move-sheet and the mouse. I believe this should be like this, so that papageorge does not disrupt the normal FICS behaviour: backward and forward navigate through the mainline stored in the server.

You can configure the background colours for the cells in the move sheet, through .papageorge.conf. I will also take your recommendation and put an option there to auto-save games on .pgn files, every time a board is closed.

**Comment by enricoT** [comment]
Ciao! Perfect work, i suspect there is a possible noise if you type: examine stoccafisso -1 and then download from pgn a game on the same worksheet. I dont understand how do i make bold  or colored in move game sheet the last move played (wich is helpful on jumping through variations...

**Comment by drestebon** [comment]
The color configurations for the move sheet are as follows:

movesheet_bg: background of the move sheet (where there is no moves)
movesheet_curr_move: background for the current move
movesheet_curr_move_n: background of the number column in the row where the current move is
movesheet_curr_line: background for the moves in the current line
movesheet_curr_line_n: background for the number column for the rows in the current line
movesheet_off: background for the moves not in the current line
movesheet_off_n: background for the number column for the rows not in the current line

Moves are marked with bold face fonts, when there is a comment for them. The comments appear as tooltips when you leave the mouse over the move and wait for a little while.

I will put some of this in the README.

**Comment by enricoT** [comment]
i dont know if it fit this thread, but, the command mexamine makes examiner 1 or more observers, i dont know if this functionality of fics, has to be handled by papageorge examine configuration or it's already in it.

**Comment by drestebon** [comment]
Thanks for pointing this out! In b5203ae4244f52d06de09ee1efda3e2a24695ff0 I added a tiny fix in the way papageorge handles style12, to account for changes in your relation to the game. With this, the board behaves as expected, once you become an examiner.

**Comment by enricoT** [comment]
examine
i run analysisbot from terminal (i made a alias me to rune analisysbot)
me

> me
> (told Analysisbot)
> :I will now be observing game 142 and giving you computer analysis.
> :[Game 142] Depth: 13  Score: -0.20  PV: 1. ... d5 2. cxd5 Nxd5 3. Nxd5 Qxd5 4.
> O-O Qd6 5. Bd2 Bg4 6. Qc2 Rad8 7. Qc4 Qe6
> Stopping Analysisbot to avoid jamming
> Restarting Analysisbot in 2 secs ...
> (told Analysisbot)
> :All your requests have been removed.

Game 142: AcCoNcIo moves: d5

Game 142: AcCoNcIo moves: cxd5

Game 142: AcCoNcIo moves: Nxd5

the position is updated on board clicking on analysisbot moves list, but moves sheet is not it's equal to precedente position

You cannot go forward unless you are on the main line.
You cannot go forward unless you are on the main line.
You cannot go forward unless you are on the main line.
ValueError: '-RBQK--R----PPBP--NP-NP-PPP--------pp---p-n---p--pp-npbpr-bq-rk-' iNotification: barbos has arrived and isn't on your notify list.

seems that in examine bot should be added a new input method ^^

**Comment by drestebon** [comment]
Hello enrico,

could you give me the position you were looking at, when analysisbot gave you that analysis, and the move you clicked that produced the problem?

**Comment by enricoT** [comment]
i cant apparently ive' found this:

examine stoccafisso -1
forw 999
it doesnt store in sheet moves the sequence, just latest move

**Comment by drestebon** [comment]
That is the expected behavior, up to now. When you issue forw 999, you get a single <12> with the state of the board after the last move. papageorge only shows everything it has. One could try to "fix" this, issuing "moves" whenever there is "holes" in the game's history. This would be a little bit messy though. In many occasions, there is no moves to fill this holes: every time a board is setup with bsetup, for example. Lecturebot does this all the time.

What you can do now to fill the holes, is to go forward or backward one move at a time.

I will explore solutions with "moves" and see how they work and keep you posted on that.

**Comment by drestebon** [comment]
Hello Acconcio,

Much of the code for the game history and move sheet is reworked. Please report here if you still have any issues with them and analysisbot.

**Comment by drestebon** [comment]
I believe the general objectives from this discussion have been achieved
